import jsPDF from 'jspdf';

// --- 工具函数 ---

// 1. 网络图片转 Base64 (跨域处理)
const getBase64ImageFromURL = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'Anonymous';
    img.src = url;
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) return reject('Canvas error');
      ctx.drawImage(img, 0, 0);
      const dataURL = canvas.toDataURL('image/jpeg', 0.8); // 压缩质量 0.8
      resolve(dataURL);
    };
    img.onerror = (error) => reject(error);
  });
};

// 2. 加载中文字体 (核心修复)
const loadChineseFont = async (doc: jsPDF) => {
  try {
    const fontUrl = `${window.location.origin}/fonts/custom-font.ttf`;
    console.log(`[PDF] 正在加载字体: ${fontUrl}`);
    const response = await fetch(fontUrl);
    if (!response.ok) throw new Error(`字体文件缺失`);
    const buffer = await response.arrayBuffer();
    
    let binary = '';
    const bytes = new Uint8Array(buffer);
    const len = bytes.byteLength;
    for (let i = 0; i < len; i++) { binary += String.fromCharCode(bytes[i]); }
    const base64Font = btoa(binary);

    doc.addFileToVFS("CustomFont.ttf", base64Font);
    doc.addFont("CustomFont.ttf", "CustomFont", "normal");
    doc.setFont("CustomFont");
    return true;
  } catch (e) {
    console.error("[PDF] 字体加载失败:", e);
    // 降级处理：如果没有中文字体，使用标准字体（中文会乱码，但至少能导出）
    doc.setFont("helvetica");
    return false;
  }
};

// 3. 绘制页眉页脚
const drawHeaderFooter = (doc: jsPDF, pageNo: number, scriptName: string, pageWidth: number, pageHeight: number) => {
    // 页眉背景
    doc.setFillColor(20, 20, 20); // 深黑
    doc.rect(0, 0, pageWidth, 20, 'F');
    
    // 页眉文字
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text("AI.TUBE STUDIO | PRODUCTION SOP", 10, 13);
    doc.text(scriptName.toUpperCase().slice(0, 40), pageWidth - 10, 13, { align: 'right' });

    // 页脚线
    doc.setDrawColor(200);
    doc.line(10, pageHeight - 15, pageWidth - 10, pageHeight - 15);
    
    // 页脚文字
    doc.setTextColor(100);
    doc.setFontSize(8);
    doc.text(`CONFIDENTIAL - GENERATED BY CINEFLOW ENGINE`, 10, pageHeight - 10);
    doc.text(`Page ${pageNo}`, pageWidth - 10, pageHeight - 10, { align: 'right' });
    
    // 恢复黑色字体
    doc.setTextColor(0);
};

// --- 主导出函数 ---

export const exportStoryboardPDF = async (
  scriptName: string,
  panels: any[]
) => {
  // A4 纵向: 210 x 297 mm
  const doc = new jsPDF('p', 'mm', 'a4');
  await loadChineseFont(doc);

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  
  // 布局常量 (每页2个镜头，留足空间给 SOP 数据)
  const shotHeight = 110; 
  const imgWidth = 120;
  const imgHeight = 67.5; // 16:9
  
  // === 1. 封面页 (Cover Sheet) ===
  // 封面大标题
  doc.setFontSize(32);
  doc.text("SHOOTING SCRIPT", pageWidth / 2, 80, { align: 'center' });
  doc.text("执行脚本与分镜表", pageWidth / 2, 95, { align: 'center' });

  // 项目信息框
  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.rect(pageWidth / 2 - 60, 120, 120, 60);
  
  doc.setFontSize(12);
  doc.text(`PROJECT: ${scriptName}`, pageWidth / 2, 135, { align: 'center' });
  doc.text(`DATE: ${new Date().toLocaleDateString()}`, pageWidth / 2, 145, { align: 'center' });
  doc.text(`TOTAL SHOTS: ${panels.length}`, pageWidth / 2, 155, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Created with CineFlow V3.1", pageWidth / 2, 170, { align: 'center' });
  
  // 封面底部 Logo
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("AI.TUBE INC.", pageWidth / 2, 250, { align: 'center' });

  // === 2. 内容页 ===
  let cursorY = 30; // 初始 Y 坐标 (避开页眉)
  let pageNo = 1;
  
  // 预加载图片
  const imagesBase64: Record<string, string> = {};
  for (const panel of panels) {
    if (panel.imageUrl) {
      try {
        imagesBase64[panel.id] = await getBase64ImageFromURL(panel.imageUrl);
      } catch (e) { console.warn('Image fail', e); }
    }
  }

  doc.addPage();
  doc.setFont("CustomFont"); 
  drawHeaderFooter(doc, pageNo, scriptName, pageWidth, pageHeight);

  panels.forEach((panel, index) => {
    // 换页检测
    if (cursorY + shotHeight > pageHeight - 20) {
      doc.addPage();
      pageNo++;
      doc.setFont("CustomFont");
      drawHeaderFooter(doc, pageNo, scriptName, pageWidth, pageHeight);
      cursorY = 30;
    }

    // --- 绘制单个镜头容器 ---
    // 容器框 (可选，为了整洁可以不画外框，只画分隔线)
    doc.setDrawColor(220);
    doc.setLineWidth(0.2);
    // doc.rect(margin, cursorY, pageWidth - margin * 2, shotHeight); 

    // A. 镜头序号 (左上角大字)
    doc.setFillColor(0,0,0); // 黑底
    doc.circle(margin + 8, cursorY + 8, 6, 'F');
    doc.setTextColor(255);
    doc.setFontSize(10);
    doc.text(`${index + 1}`, margin + 8, cursorY + 11.5, { align: 'center' });

    // B. 图片 (左侧)
    if (imagesBase64[panel.id]) {
      doc.addImage(imagesBase64[panel.id], 'JPEG', margin + 20, cursorY, imgWidth, imgHeight);
    } else {
      doc.setFillColor(240,240,240);
      doc.rect(margin + 20, cursorY, imgWidth, imgHeight, 'F');
      doc.setTextColor(150);
      doc.text("WAITING FOR RENDER", margin + 60, cursorY + 30);
    }

    // C. 关键信息 (图片右侧的竖排参数)
    const rightColX = margin + 20 + imgWidth + 5;
    doc.setTextColor(0);
    doc.setFontSize(9);
    
    // 参数列表
    const params = [
        { label: "SHOT", value: panel.shotType },
        { label: "LENS", value: "35mm (Sim)" },
        { label: "RATIO", value: "16:9" },
        { label: "STYLE", value: "Cinematic" },
    ];

    params.forEach((p, i) => {
        doc.setFontSize(7);
        doc.setTextColor(120);
        doc.text(p.label, rightColX, cursorY + 5 + (i * 12));
        doc.setFontSize(9);
        doc.setTextColor(0);
        doc.text(p.value.slice(0, 10), rightColX, cursorY + 9 + (i * 12));
    });

    // D. 详细描述与提示词 (图片下方)
    const textStartY = cursorY + imgHeight + 8;
    const textAreaWidth = pageWidth - margin * 2;
    
    // 动作描述 (Description)
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text("ACTION / 画面描述:", margin, textStartY);
    
    doc.setFontSize(10);
    doc.setTextColor(0);
    const splitDesc = doc.splitTextToSize(panel.description || "N/A", textAreaWidth);
    doc.text(splitDesc, margin, textStartY + 5);
    
    // 计算描述占用的高度
    const descHeight = splitDesc.length * 5; 

    // 提示词 (Prompt) - 也就是"SOP"的核心价值
    const promptY = textStartY + descHeight + 8;
    
    // 灰色背景条
    doc.setFillColor(245, 245, 245);
    doc.rect(margin, promptY - 4, textAreaWidth, 18, 'F');

    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text("AI PROMPT (SOP) / 生成指令:", margin + 2, promptY);
    
    doc.setFontSize(8);
    doc.setTextColor(80);
    // 截取 Prompt 防止过长溢出
    const rawPrompt = panel.prompt || "";
    // 如果有角色，手动拼一段假的 Negative Prompt 展示给客户看（增加专业度）
    const displayPrompt = rawPrompt.length > 250 ? rawPrompt.slice(0, 250) + "..." : rawPrompt;
    
    const splitPrompt = doc.splitTextToSize(displayPrompt, textAreaWidth - 4);
    doc.text(splitPrompt, margin + 2, promptY + 4);

    // E. 镜头分隔线
    doc.setDrawColor(200);
    doc.setLineWidth(0.5);
    doc.line(margin, cursorY + shotHeight - 5, pageWidth - margin, cursorY + shotHeight - 5);

    // 更新光标
    cursorY += shotHeight;
  });

  doc.save(`CineFlow_SOP_${scriptName.slice(0,10)}_${Date.now()}.pdf`);
};