import jsPDF from 'jspdf';

// --- 类型定义 ---
interface ExportMeta {
  projectName: string;
  author: string;
  notes: string;
}

// --- 工具函数 ---

// 1. 网络图片转 Base64
const getBase64ImageFromURL = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'Anonymous';
    img.src = url;
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) return reject('Canvas error');
      ctx.drawImage(img, 0, 0);
      const dataURL = canvas.toDataURL('image/jpeg', 0.8);
      resolve(dataURL);
    };
    img.onerror = (error) => reject(error);
  });
};

// 2. 加载中文字体
const loadChineseFont = async (doc: jsPDF) => {
  try {
    const fontUrl = `${window.location.origin}/fonts/custom-font.ttf`;
    console.log(`[PDF] 正在加载字体: ${fontUrl}`);
    const response = await fetch(fontUrl);
    if (!response.ok) throw new Error(`字体文件缺失`);
    const buffer = await response.arrayBuffer();
    
    let binary = '';
    const bytes = new Uint8Array(buffer);
    const len = bytes.byteLength;
    for (let i = 0; i < len; i++) { binary += String.fromCharCode(bytes[i]); }
    const base64Font = btoa(binary);

    doc.addFileToVFS("CustomFont.ttf", base64Font);
    doc.addFont("CustomFont.ttf", "CustomFont", "normal");
    doc.setFont("CustomFont");
    return true;
  } catch (e) {
    console.error("[PDF] 字体加载失败:", e);
    doc.setFont("helvetica");
    return false;
  }
};

// 3. 绘制页眉页脚
const drawHeaderFooter = (doc: jsPDF, pageNo: number, meta: ExportMeta, pageWidth: number, pageHeight: number) => {
    // 页眉背景
    doc.setFillColor(20, 20, 20);
    doc.rect(0, 0, pageWidth, 20, 'F');
    
    // 页眉文字
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text("AI.TUBE STUDIO | PRODUCTION SOP", 10, 13);
    doc.text(meta.projectName.toUpperCase().slice(0, 40), pageWidth - 10, 13, { align: 'right' });

    // 页脚线
    doc.setDrawColor(200);
    doc.line(10, pageHeight - 15, pageWidth - 10, pageHeight - 15);
    
    // 页脚文字
    doc.setTextColor(100);
    doc.setFontSize(8);
    const authorText = meta.author ? `DIR: ${meta.author.toUpperCase()} | ` : "";
    doc.text(`${authorText}CONFIDENTIAL - GENERATED BY CINEFLOW`, 10, pageHeight - 10);
    doc.text(`Page ${pageNo}`, pageWidth - 10, pageHeight - 10, { align: 'right' });
    
    doc.setTextColor(0);
};

// --- 主导出函数 ---

export const exportStoryboardPDF = async (
  meta: ExportMeta, // 🟢 变更：接收完整元数据对象
  panels: any[]
) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  await loadChineseFont(doc);

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const shotHeight = 110; 
  const imgWidth = 120;
  const imgHeight = 67.5; 
  
  // === 1. 封面页 (Cover Sheet) ===
  doc.setFontSize(32);
  doc.text("SHOOTING SCRIPT", pageWidth / 2, 60, { align: 'center' });
  doc.text("执行脚本与分镜表", pageWidth / 2, 75, { align: 'center' });

  // 项目信息框
  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.rect(pageWidth / 2 - 70, 100, 140, 80);
  
  doc.setFontSize(12);
  doc.text(`PROJECT: ${meta.projectName || "Untitled"}`, pageWidth / 2, 115, { align: 'center' });
  doc.text(`DIRECTOR: ${meta.author || "AI Creator"}`, pageWidth / 2, 125, { align: 'center' });
  doc.text(`DATE: ${new Date().toLocaleDateString()}`, pageWidth / 2, 135, { align: 'center' });
  doc.text(`TOTAL SHOTS: ${panels.length}`, pageWidth / 2, 145, { align: 'center' });
  
  if (meta.notes) {
      doc.setFontSize(10);
      doc.setTextColor(100);
      const splitNotes = doc.splitTextToSize(`NOTES: ${meta.notes}`, 120);
      doc.text(splitNotes, pageWidth / 2, 160, { align: 'center' });
  }
  
  // 底部 Logo
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("AI.TUBE INC.", pageWidth / 2, 260, { align: 'center' });

  // === 2. 内容页 ===
  let cursorY = 30;
  let pageNo = 1;
  
  const imagesBase64: Record<string, string> = {};
  for (const panel of panels) {
    if (panel.imageUrl) {
      try { imagesBase64[panel.id] = await getBase64ImageFromURL(panel.imageUrl); } catch (e) {}
    }
  }

  doc.addPage();
  doc.setFont("CustomFont"); 
  drawHeaderFooter(doc, pageNo, meta, pageWidth, pageHeight);

  panels.forEach((panel, index) => {
    if (cursorY + shotHeight > pageHeight - 20) {
      doc.addPage();
      pageNo++;
      doc.setFont("CustomFont");
      drawHeaderFooter(doc, pageNo, meta, pageWidth, pageHeight);
      cursorY = 30;
    }

    // 镜头序号
    doc.setFillColor(0,0,0);
    doc.circle(margin + 8, cursorY + 8, 6, 'F');
    doc.setTextColor(255);
    doc.setFontSize(10);
    doc.text(`${index + 1}`, margin + 8, cursorY + 11.5, { align: 'center' });

    // 图片
    if (imagesBase64[panel.id]) {
      doc.addImage(imagesBase64[panel.id], 'JPEG', margin + 20, cursorY, imgWidth, imgHeight);
    } else {
      doc.setFillColor(240, 240, 240);
      doc.rect(margin + 20, cursorY, imgWidth, imgHeight, 'F');
      doc.setTextColor(150);
      doc.text("WAITING FOR RENDER", margin + 60, cursorY + 30);
    }

    // 右侧参数
    const rightColX = margin + 20 + imgWidth + 5;
    doc.setTextColor(0);
    const params = [
        { label: "SHOT", value: panel.shotType },
        { label: "ENV", value: panel.environment || "N/A" },
        { label: "CHAR", value: panel.characterId ? "Yes" : "No" },
    ];
    params.forEach((p, i) => {
        doc.setFontSize(7);
        doc.setTextColor(120);
        doc.text(p.label, rightColX, cursorY + 5 + (i * 12));
        doc.setFontSize(9);
        doc.setTextColor(0);
        doc.text(p.value.slice(0, 10), rightColX, cursorY + 9 + (i * 12));
    });

    // 下方 Prompt
    const textStartY = cursorY + imgHeight + 8;
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text("ACTION / 画面描述:", margin, textStartY);
    
    doc.setFontSize(10);
    doc.setTextColor(0);
    const splitDesc = doc.splitTextToSize(panel.description || "", pageWidth - margin * 2);
    doc.text(splitDesc, margin, textStartY + 5);
    
    const descHeight = splitDesc.length * 5; 
    const promptY = textStartY + descHeight + 8;
    
    doc.setFillColor(245, 245, 245); // 修复后的灰色
    doc.rect(margin, promptY - 4, pageWidth - margin * 2, 18, 'F');

    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text("AI PROMPT (SOP):", margin + 2, promptY);
    
    doc.setFontSize(8);
    doc.setTextColor(80);
    const rawPrompt = panel.prompt || "";
    const displayPrompt = rawPrompt.length > 250 ? rawPrompt.slice(0, 250) + "..." : rawPrompt;
    const splitPrompt = doc.splitTextToSize(displayPrompt, pageWidth - margin * 2 - 4);
    doc.text(splitPrompt, margin + 2, promptY + 4);

    doc.setDrawColor(200);
    doc.setLineWidth(0.5);
    doc.line(margin, cursorY + shotHeight - 5, pageWidth - margin, cursorY + shotHeight - 5);

    cursorY += shotHeight;
  });

  doc.save(`CineFlow_SOP_${meta.projectName.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};